project:
  type: hugo
  render:
    - content/blog/**/index.qmd
    - content/blog/**/index.ipynb

execute:
  eval: true
  echo: true
  freeze: auto
  warning: false
  message: false

jupyter: python3

format:
  hugo-md:
    code-fold: true
    code-summary: "Show code"
